package com.sendbird.uikit_messaging_android.consts

object StringSet {
    const val CHANNEL_NAME = "CHANNEL_NAME"
    const val CHANNEL_ID = "CHANNEL_ID"
    const val KEY_CHANNEL_URL = "KEY_CHANNEL_URL"
    const val PUSH_REDIRECT_CHANNEL = "PUSH_REDIRECT_CHANNEL"
    const val PUSH_REDIRECT_MESSAGE_ID = "PUSH_REDIRECT_MESSAGE_ID"
    const val SETTINGS_USE_HEADER = "SETTINGS_USE_HEADER"
    const val SETTINGS_USE_DO_NOT_DISTURB = "SETTINGS_USE_DO_NOT_DISTURB"
    const val SB_LIVE_TYPE = "SB_LIVE_TYPE"
    const val SB_COMMUNITY_TYPE = "SB_COMMUNITY_TYPE"
    const val KEY_INPUT_TEXT = "KEY_INPUT_TEXT"
    const val sendbird = "sendbird"
    const val channel = "channel"
    const val channel_url = "channel_url"
    const val message_id = "message_id"
    const val message = "message"
    const val sender = "sender"
    const val name = "name"
    const val profile_url = "profile_url"
    const val id = "id"
    const val tags = "tags"
    const val creator_info = "creator_info"
    const val thumbnail_url = "thumbnail_url"
    const val live_channel_url = "live_channel_url"
}
